name: Build Book

on: [push]

jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: |
          git lfs checkout
          git lfs pull

      - name: Install dependencies
        run: |
          sudo apt update -q
          sudo apt-get install -qy texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-xetex latexmk
          sudo pip3 install -r requirements.txt

      - name: Setup required data
        run: |
          cp examples/working_with_data/pandas/tree-census-data.zip src/working_with_data/pandas
          cd src/working_with_data/pandas
          unzip tree-census-data.zip

      - name: Build HTML version
        run: make html

      - name: Build PDF version
        run: make latexpdf
